# Generated by Django 5.2.14 on 2026-06-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
