# Generated by Django 5.2.14 on 2026-06-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_action_status_module_status_role_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
