# Generated by Django 5.2.14 on 2026-06-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_moduleactionassoc_rolepermission_module_action_assoc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'module_action_assoc')},
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='action',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='module',
        ),
    ]
