# Generated by Django 5.2.14 on 2026-06-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usercompanyassoc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercompanyassoc',
            unique_together=set(),
        ),
    ]
