# Generated by Django 5.2.14 on 2026-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('action_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('before_input', models.JSONField(blank=True, null=True)),
                ('after_input', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activity_logs',
            },
        ),
    ]
