# Generated by Django 5.2.14 on 2026-06-09 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action_name', 'timestamp'], name='user_activi_action__200c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['timestamp'], name='user_activi_timesta_8378ef_idx'),
        ),
    ]
