# Generated by Django 5.2.14 on 2026-06-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_alter_status_options_documenttype'),
        ('master_data', '0005_customer_company'),
    ]

    operations = [
    ]
