# Generated by Django 5.2.14 on 2026-06-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_merge_20260618_1740'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_type_assocs', to='master_data.customer')),
                ('document_type', models.ForeignKey(db_column='document_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_assocs', to='master_data.documenttype')),
                ('export_country', models.ForeignKey(blank=True, db_column='export_country_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_document_assocs', to='master_data.country')),
                ('import_country', models.ForeignKey(blank=True, db_column='import_country_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_document_assocs', to='master_data.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_doc_assoc',
                'ordering': ['-updated_at'],
            },
        ),
    ]
