# Generated by Django 5.2.14 on 2026-06-19 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_merge_0006_merge_20260619_1130_0007_customerdocassoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('carrier_name', models.CharField(max_length=255, unique=True)),
                ('carrier_scac', models.CharField(blank=True, max_length=100)),
                ('transport', models.ForeignKey(blank=True, db_column='transport_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carriers', to='master_data.transportmode')),
                ('web_link', models.CharField(blank=True, max_length=255)),
                ('logo', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_carriers',
            },
        ),
    ]
