# Generated by Django 5.2.14 on 2026-06-22 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_carrier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(db_column='carrier_id', on_delete=django.db.models.deletion.CASCADE, related_name='carrier_contacts', to='master_data.carrier')),
                ('type', models.CharField(blank=True, max_length=20)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_contacts', to='master_data.customer')),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_contacts', to='master_data.company')),
                ('transport', models.ForeignKey(blank=True, db_column='transport_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier_contacts_transport', to='master_data.transportmode')),
                ('shipment_type', models.CharField(blank=True, max_length=20)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_contacts_country', to='master_data.country')),
                ('export_country', models.ForeignKey(blank=True, db_column='export_country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_contacts_export', to='master_data.country')),
                ('import_country', models.ForeignKey(blank=True, db_column='import_country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_contacts_import', to='master_data.country')),
                ('primary_transport', models.ForeignKey(blank=True, db_column='primary_transport_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier_contacts_primary_transport', to='master_data.transportmode')),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_contacts', to='master_data.city')),
                ('service_type', models.CharField(blank=True, max_length=50)),
                ('emails', models.TextField(blank=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auto_approve', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrier_contacts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLspAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='lsp_assocs', to='master_data.customer')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='lsp_assocs', to='master_data.company')),
                ('carrier', models.ForeignKey(db_column='carrier_id', on_delete=django.db.models.deletion.PROTECT, related_name='lsp_assocs', to='master_data.carrier')),
                ('transport', models.ForeignKey(blank=True, db_column='transport_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lsp_assocs', to='master_data.transportmode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_lsp_assoc',
                'ordering': ['-updated_at'],
            },
        ),
    ]
