# Generated by Django 5.2.14 on 2026-06-25 05:44

import django.core.validators
import django.db.models.deletion
import master_data.models.custom_officer_shift
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_carriercontact_customerlspassoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsOfficerShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer', models.ForeignKey(help_text='Customs officer assigned to this shift schedule.', on_delete=django.db.models.deletion.CASCADE, related_name='officer_shifts', to=settings.AUTH_USER_MODEL)),
                ('start_date', models.DateField(db_index=True, help_text='Date from which this shift schedule becomes effective.')),
                ('end_date', models.DateField(blank=True, db_index=True, help_text='Date until which this shift schedule remains effective. Leave blank for an open-ended schedule.', null=True)),
                ('shift_start_time', models.TimeField(help_text='Daily shift start time in 24-hour format (HH:MM).')),
                ('shift_end_time', models.TimeField(help_text='Daily shift end time in 24-hour format (HH:MM).')),
                ('working_days', models.JSONField(default=list, help_text="Working days. Allowed values: MON, TUE, WED, THU, FRI, SAT, SUN. Example: ['MON', 'TUE', 'WED', 'THU', 'FRI']", validators=[master_data.models.custom_officer_shift.validate_working_days])),
                ('break_time', models.PositiveSmallIntegerField(default=30, help_text='Break duration in minutes during the shift.', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available_today', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the officer is available for scheduling today.')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Active or inactive status of the shift schedule.')),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customs Officer Shift',
                'verbose_name_plural': 'Customs Officer Shifts',
                'db_table': 'customs_officer_shifts',
                'ordering': ['officer', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Inspection area name.', max_length=250, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Unique inspection area code.', max_length=100, unique=True)),
                ('start_time', models.TimeField(db_index=True, help_text='Operational start time in 24-hour format.')),
                ('end_time', models.TimeField(db_index=True, help_text='Operational end time in 24-hour format.')),
                ('avg_inspection_time', models.PositiveSmallIntegerField(help_text='Average inspection duration in minutes.', validators=[django.core.validators.MinValueValidator(1)])),
                ('interval_time', models.PositiveSmallIntegerField(help_text='Buffer/break time between inspections in minutes.', validators=[django.core.validators.MinValueValidator(0)])),
                ('special_operation', models.BooleanField(default=False, help_text='Indicates whether the area supports special inspection operations.')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Active/Inactive status.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inspection Area',
                'verbose_name_plural': 'Inspection Areas',
                'db_table': 'inspection_areas',
                'ordering': ['name'],
            },
        ),
    ]
