# Generated by Django 5.2.14 on 2026-06-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_customsofficershift_inspectionarea'),
        ('master_data', '0011_substatus'),
    ]

    operations = [
    ]
