# Generated by Django 5.2.14 on 2026-06-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_emailtemplatetypes_emailtemplatehash_emailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='company',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='carriercontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customerlspassoc',
            name='company',
        ),
    ]
