# Generated by Django 5.2.14 on 2026-06-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_remove_company_created_by_remove_company_customer_and_more'),
        ('users', '0009_usercustomerassoc_delete_usercompanyassoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
