# Generated by Django 5.2.14 on 2026-06-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_delete_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'managed': False, 'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'managed': False, 'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='seaport',
            options={'managed': False, 'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='transportmode',
            options={'managed': False, 'ordering': ['code']},
        ),
    ]
